### PR TITLE
#1755: Replace 'pickle' with custom json encoder

### LINKED ISSUE #1755: Replace 'pickle' with custom json encoder (SVC)
We will consider replacing the `pickle` [implementation](https://github.com/jeff1evesque/machine-learning/issues/1752) in `serialize_model.py` with a custom json encoder, and custom json decoder for the SVC instance.

### PR DESCRIPTION
**Pull request by protojas**
Closes #1755

### CODE REVIEW

**Comment by jeff1evesque** [comment]
This PR is with respect to milestone 0.6. So, we'll need to replace the current PR, with a new PR into the `master` branch. However, seems you have some milestone 0.9 items included in this PR.  We can let Travis run its unit test, to help identify any problems.  But, I'll need to create a separate new PR of this when you're ready. Basically, we are going to have to remove 0.9 items for the new PR.  You may need to blow away, and delete your local clone, and redo `git clone`, to ensure you have a clean, and segregated `master` branch from the `milestone-0.9` branch, for future stuff.

**Comment by jeff1evesque** [comment]
Actually, if your `master` branch is separate from `milestone-0.9`:

```bash
git checkout master
git branch -d feature-1755
git push origin :feature-1755 -f
git checkout feature-1755 master
# recommit your stuff
```

Otherwise, you'll have to delete the entire directory, to create a clean `feature-1755`. If I were to `git  upstream` your branch, it would need a bunch of messy `git rebase`, which is usually not recommended.

**Comment by protojas** [comment]
When I did the last step of this I got:
```
~\Documents\GitHub\machine-learning [master ≡ +2 ~5 -0 !]> git checkout feature-1755 master
error: pathspec 'feature-1755' did not match any file(s) known to git.
error: pathspec 'master' did not match any file(s) known to git.
```

**Comment by protojas** [comment]
do I need to put `-b`?

**Comment by jeff1evesque** [comment]
You're right need that `-b`.

**Comment by protojas** [comment]
how should I do the pull request after I re-push everything?

**Comment by protojas** [comment]
and by everything i mean the two serializer.py's

**Pull request closed without merging**
