### PR TITLE
#3041: Create bootstrap aggregation regressor

### LINKED ISSUE #3041: Create bootstrap aggregation wrapper (regressor)
We need to create a python function for the bootstrap aggregation method.  This function, should accept a variety of our predefined estimators:

- `SVR` (#3035)
- `KNeighborsRegressor` (#3033)
- `RandomForestRegressor` (#3039)
- `BaggingRegressor` (#3034)

**Note:** this issue is a successor of #3025.

### PR DESCRIPTION
**Pull request by jeff1evesque**
Resolves #3041.

### CODE REVIEW

**Comment by jeff1evesque** [comment]
@protojas, are the adjustments fairly decent, with respect to the bagging ensembler? Do you have any recommendations, on additional changes to any of the files in this PR?

**Comment by protojas** [comment]
@jeff1evesque  looks ok from what I can see

**Comment by jeff1evesque** [comment]
I'm starting to wonder the use of `bagR.py`. Do you think we need it? It seems like another wrapper, with no added benefit, to your `baggen.py`.

**Comment by protojas** [comment]
@jeff1evesque it's for regression, it gives a True instead of a False compared to bagc.py, which tells baggen to use a regressor instead of a classifier for the basic decision tree case

**Comment by jeff1evesque** [comment]
I think we can go straight to your `baggen.py` (renamed to `bagger.py`), and remove the intermediary `bagR.py`.  Because, we can simply switch the implementation based on the `model` argument supplied.  For example, if `model is ['bagc'`](https://github.com/jeff1evesque/machine-learning/blob/cd7fcc217a75457969ca329d32ea5973a0f6c4ce/brain/session/model/bagger.py#L105), then implement the classification method. Otherwise, if `model is ['bagr'](https://github.com/jeff1evesque/machine-learning/blob/cd7fcc217a75457969ca329d32ea5973a0f6c4ce/brain/session/model/bagger.py#L123)`, then implement the regressor method.

**Comment by protojas** [comment]
ok. are you planning to do one big if/else for if model=bagknnc/bagknnr/bagrfr/bagrfc/bagsvc/bagsvr too then? i was assuming you'd want consistency for the api to the web interface

**Comment by jeff1evesque** [comment]
I think the original [`baggen.py`](https://github.com/jeff1evesque/machine-learning/pull/3061/commits/47761937e7d8f72b91713080bcf225f0d1c0ab57) you submitted had `IF/ELSE` built into the `bagging`, and `baggen` functions. So, it seems they are already by design, indicating the `if` switch statements.

**Comment by protojas** [comment]
yea but bagging using knn and bagging using svc and bagging using decision trees all have different parameters

so the wrappers i made in bagknnc.py/bagsvc.py/bagc.py/bagrfc.py and their regression counterparts all have different parameters for the web interface to use

so if you remove bagc.py and bagr.py you'd have a slightly different interface in comparison to the other wrappers (you'll have to pass `None` and `True`\`False` to the baggen.py for the `be` argument where the other wrappers don't use the `be` argument or the `regression` argument)

which is fine with me, lol, just letting you know it's going to have 2 extra parameters for using decision trees in comparison to using the other wrappers

**Comment by jeff1evesque** [comment]
Ah, ok. Maybe we can define them with predefined values, like `None`, or `False`? I want to get this issue merged, so I can at least build the programmatic api for it. I was hoping the web-interface.  But, I'm not sure how long @Vitao18 will take with #3047. Been doing too much js the last 2 weeks.

**Comment by protojas** [comment]
`None` can be predefined (and I think it is) but regression will need to be changed on whether you want a classifier or a regressor. so you can define it as `False` but you'll have to specify `True` when you're doing a regression with decision trees

**Comment by protojas** [comment]
One way to do this might be
```
rswitch= {"bagc": False, "bagknnc": False, "bagrfc": False, "bagsvc": False, "bagr": True, "bagknnr": True, "bagrfr": True, "bagsvr": True}

regression = rswitch[model]
```

maybe use a `defaultdict` or a try/catch so that if its not one of those it gives an error or picks one at random

**Comment by jeff1evesque** [comment]
What's wrong with:

```python
    # set up the ensembler
    if model == list_model_type[3]:
        bagger = sklearn.ensemble.BaggingClassifier(
            base_estimator=be,
            n_estimators=k,
            max_samples=samples,
            max_features=features,
            verbose=0
        )
    elif model == list_model_type[4]:
        bagger = sklearn.ensemble.BaggingRegressor(
            base_estimator=be,
            n_estimators=k,
            max_samples=samples,
            max_features=features,
            verbose=0
        )
```

**Comment by protojas** [comment]
what do you do if it's list_model_type[5],[6],[7],[8]...?

bagknnc will have to be a different list_model_type from bagc if you want to be able to put the parameters of knn in as well as the bagging parameters

**Comment by jeff1evesque** [comment]
I was just thinking we could restructure the [`application.yaml`](https://github.com/jeff1evesque/machine-learning/blob/master/hiera/application.yaml#L30-L32), such that there is a subgrouping:

```yaml
    model_type:
        classifiers:
            - svm
            - bagc
        regressors:
            - svr
            - bagr
```

But, that would mean we would need to refactor in other places.  Maybe we can prep for that, with an uglier solution?  We could temporarily maintain such a list:

```python
    classifiers = [list_model_type[4], list_model_type[x]]
    regressors = [list_model_type[3], list_model_type[y]]
```

This would mean that the order of items in the `application.yaml` is important. Then, we can simply check if the supplied `model`, which could be a value of `bagr`, is in the `regressors` list.

**Comment by protojas** [comment]
ok that seems like a good idea

**Comment by jeff1evesque** [comment]
When travis ci finishes, and checks passes, I'm going to merge this, unless you see anything wrong.

**Comment by protojas** [comment]
nothing here, go for it

**Pull request merged**
