### PR TITLE
#2767: Created data_attributes.rst and linked it in the README.md

### PR DESCRIPTION
**Pull request by rahul-kumi**
PR raised to resolve issue #2767.

### CODE REVIEW

**Comment by rahul-kumi** [comment]
Thank you @jeff1evesque, for the guidance.

**Comment by jeff1evesque** [comment]
I would remove your committed [`src/jsx/README.rst `](https://github.com/rahul-kumi/machine-learning/blob/b689ae3769be2a0f9540261db6a40efdeaee936e/src/jsx/README.rst), and add back the current [`src/jsx/README.md`](https://github.com/jeff1evesque/machine-learning/blob/master/src/jsx/README.md):

```bash
$ git rm /path/to/machine-learning/src/jsx/README.rst
$ vi /path/to/machine-learning/src/jsx/README.md
## copy back https://github.com/jeff1evesque/machine-learning/blob/master/src/jsx/README.md
$ git add path/to/machine-learning/src/jsx/README.md
$ git commit -m "#2767: README.md, renamed from 'README.rst'
$ git push origin feature-2767
```

Then, I would remove the following from the main [`README.md`](https://github.com/rahul-kumi/machine-learning/blob/b689ae3769be2a0f9540261db6a40efdeaee936e/README.md#data-attributes):

>The [Data attributes](https://github.com/jeff1evesque/machine-learning/blob/master/documentation/programmatic/data_attributes.rst) implemented.

And, replace it as follows:

>**Note:** various `data` [attributes](https://github.com/jeff1evesque/machine-learning/documentation/programmatic/data_attributes.rst) can be nested in above `POST` request.

```bash
$ git add /path/to/machine-learning/README.md
$ git commit -m "#2767: README.md, minor language change"
$ git push origin feature-2767
```

Lastly, I think you've forgot to add content to your committed [`documentation/programmatic/data_attributes.rst `](https://github.com/rahul-kumi/machine-learning/blob/b689ae3769be2a0f9540261db6a40efdeaee936e/documentation/programmatic/data_attributes.rst):

```bash
$ git add /path/to/machine-learning/documentation/programmatic/data_attributes.rst
$ git commit -m "#2767: data_attributes.rst, add content
$ git push origin feature-2767
```

**Note:** I notice you're working on your `master` branch.  After you submit the above changes, try to run `git checkout -b feature-2767`, and resubmit a new pull request.

**Comment by jeff1evesque** [comment]
If you performed the above suggested commits, then run `git checkout -b feature-2767`, all your commits should be copied, and also implemented on the `feature-2767` branch you created.  This is the branch you should resubmit the pull request on.

**Comment by rahul-kumi** [comment]
@jeff1evesque, I was unsure of the contents to be added in the data_attributes.rst file.
Can I get a heads up regarding the contents?

**Comment by jeff1evesque** [comment]
For now, just add the following into `documentation/programmatic/data_attributes.rst:`: 

>
-    SVM datasets
  -      dataset url
  -      file upload
-    SVR datasets
  -      dataset url
  -      file upload

>**Note:** the content of each of the above files, can substituted for the above data attribute.
Data Attributes

>The following (non-exhaustive) properties define the above implemented data attribute:

>
  -  `model_id`: the numeric id value, of the generated model in the nosql datastore
  -  `model_type`: corresponds to the desired model type, which can be one of the following:
    - `classification`
    - `regression`
  -  session_id: the numeric id value, that represents the dataset stored in the sql database.
  -  dataset_type: corresponds to one of the following types:
      -  dataset_url: indication that the supplied dataset will be url references
      -  file_upload: indication that the supplied dataset(s) will be defined as a json string within the dataset attribute
 -   session_type: corresponds to one of the following session types:
      -  data_new
      -  data_append
      -  model_generate
      -  model_predict
 -   svm_dataset_type: corresponds to one of the following dataset types:
      -  json_string: indicate that the dataset is being sent via a post request
 -   sv_kernel_type: the type of kernel to apply to the support vector model_type:
      -  linear
      -  polynomial
      -  rbf
      -  sigmoid
 -   prediction_input[]: an array of prediction input, supplied to the generated model to compute a prediction

**Comment by jeff1evesque** [comment]
Just link them as they currently are implemented, in the current [`README.md`](https://github.com/jeff1evesque/machine-learning#programmatic-interface).

**Comment by jeff1evesque** [comment]
Closing this pull request per https://github.com/jeff1evesque/machine-learning/pull/2769.

**Pull request closed without merging**
