### PR TITLE
#3049: Create AdaBoost Wrapper (Classifier)

### LINKED ISSUE #3049: Create AdaBoost Wrapper (Classifier)
Create a python function for the ada boost classifier methods which supports SVC, KNN, RF, and normal decision trees.

### PR DESCRIPTION
**Pull request by protojas**
Closes #3049

### CODE REVIEW

**Comment by jeff1evesque** [comment]
I'm going to do some cosmetics to satisfy the gitmagic bot.  In the future, avoid doing any manual `git merge` on the command line, and keep commit messages under 55 characters.  I should be done soon.

**Comment by jeff1evesque** [comment]
Can you run the following:

```bash
git check out feature-3049
git remote -v
git remote remove upstream
git remote add upstream https://jeff1evesque@github.com/jeff1evesque/machine-learning.git
git pull upstream feature-3049
git remote -v
git remote remove upstream
git remote add upstream https://protojas@github.com/protojas/machine-learning.git
git push upstream feature-3049
```

That should fix the commits messages.

**Comment by protojas** [comment]
ok

**Comment by jeff1evesque** [comment]
Since the PR is off your `protojas/feature-3049`, I would have needed to submit a PR to your branch, so you could submit this PR. But, if you pull my reference, it should suck up my adjustments, in your git branch.

**Comment by jeff1evesque** [comment]
I'm not quite sure what happened with this PR. I'm going to reopen another.

**Pull request closed without merging**
