### PR TITLE
README.md to README.rst conversion throughout the repo

### PR DESCRIPTION
**Pull request by rahul-kumi**
I have converted all the README.md files to README.rst file, except those README.md files present in the root directory.
please mention if you want to convert the other '*.md' files to be converted to '*.rst'

pull request raised with reference to #2650

### CODE REVIEW

**Comment by jeff1evesque** [comment]
The requirements are changing.  We're going to keep all current `README.md`'s in the repository.  However, we will try to be similar to [scikit-learn](http://scikit-learn.org/stable/), and their current [`doc/`](https://github.com/scikit-learn/scikit-learn/tree/master/doc) directory.  This will allow us to mirror the directory to be created, and generate a corresponding website with all our documentation (possibly using the [sphinx](http://www.sphinx-doc.org/en/stable/) generator).

That being said, I would move the following for the main `README.md`  into `documentation/programmatic-api/data_attribute.rst`:

>Some additional sample files have been provided, which outline how the data attribute implement should be implemented, with respect to the above post implementation:

>    SVM datasets
        dataset url
        file upload
    SVR datasets
        dataset url
        file upload

>**Note:** the content of each of the above files, can substituted for the above data attribute.
Data Attributes

>The following (non-exhaustive) properties define the above implemented data attribute:

>
  -  `model_id`: the numeric id value, of the generated model in the nosql datastore
  -  `model_type`: corresponds to the desired model type, which can be one of the following:
        - `classification`
        - `regression`
  -  session_id: the numeric id value, that represents the dataset stored in the sql database.
  -  dataset_type: corresponds to one of the following types:
      -  dataset_url: indication that the supplied dataset will be url references
      -  file_upload: indication that the supplied dataset(s) will be defined as a json string within the dataset attribute
 -   session_type: corresponds to one of the following session types:
      -  data_new
      -  data_append
      -  model_generate
      -  model_predict
 -   svm_dataset_type: corresponds to one of the following dataset types:
      -  json_string: indicate that the dataset is being sent via a post request
 -   sv_kernel_type: the type of kernel to apply to the support vector model_type:
      -  linear
      -  polynomial
      -  rbf
      -  sigmoid
 -   prediction_input[]: an array of prediction input, supplied to the generated model to compute a prediction

If you'd like to help out, I could use your help moving the above snippet.  That should be one issue.  Then, there should be `documentation/README.md`, and `documentation/index.rst`.  Both of these, should be their own issue.  Also, when you commit code, you should follow the [best practices](https://github.com/jeff1evesque/machine-learning/blob/master/contributing.md#committing-code) outlined in the projects [contributing.md](https://github.com/jeff1evesque/machine-learning/blob/master/contributing.md).  This also means properly [naming branches](https://github.com/jeff1evesque/machine-learning/blob/master/contributing.md#creating-git-branch) when committing code.  This will allow other people to easily look at the corresponding issues, and quickly review the committed code, because prefixing your commits, will tag the issue with that commit.\

Lots of things will need to be documented in yet to be created `documentation/` directory.  If you could help with that, with the commit practices, that would be a big  help.  Issues like #2765 will eventually live there, and allow other developers in the future to stress test the application.  This will allow developers to quickly ascertain how to accomplish stress testing, rather than digging through past issues, which would be 2x more difficult if commits weren't tagged in the corresponding issue.

**Comment by rahul-kumi** [comment]
jeff1evesque, I am a newbie, so apologies for the poor style of contribution. 
I am not sure if I can take up so much work that you have mentioned in the comment.
Help!

**Comment by jeff1evesque** [comment]
@rahul-kumi, no apologies necessary.  I have a [simple issue](https://github.com/jeff1evesque/machine-learning/issues/27670) if you'd like to help out, it should take less than 15 minutes.  I've outlined the `git` commands you can execute on your host machine.

**Comment by jeff1evesque** [comment]
In the meantime, I'm going to close this pull request, on the premise of changing requirements.

**Pull request closed without merging**
