### PR TITLE
#3047: Change React.Class to ES6 Class syntax

### LINKED ISSUE #3047: Replace 'createClass' with pure javascript classes
We need to replace all our current reactjs `React.createClass({ // ... })`, with pure javascript classes. This will help avoid the following current warning:

>content.min.js:35 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

createclass

### PR DESCRIPTION
**Pull request by Vitao18**
Resolves #3047

### CODE REVIEW

**Comment by jeff1evesque** [comment]
Don't worry about the commit message length for now. I can fix that for you, when I get home. However, keep it in the back of your mind for next time.  However, I'll need to check your PR, by doing a corresponding `vagrant up` build of it, and making sure all front end stuff works.

**Comment by jeff1evesque** [comment]
I fixed your commit messages (I think).  Did have one problem, resulting me reverting your changes to `register.jsx`.  So, you'll need to reapply your changes to it after:

```bash
git remote remove upstream
git remote add upstream https://jeff1evesque@github.com/jeff1evesque/machine-learning.git
git pull upstream feature-3047
git remote remove upstream
git remote add upstream https://vitao18@github.com/vitao18/machine-learning.git
# fix changes to `register.jsx`
git commit -m "#3047: register.jsx, fixed syntax"
git push upstream feature-3047
```

**Comment by jeff1evesque** [comment]
The travis ci is breaking during its linting process of eslint. I think you should take this opportunity to update [`eslint.json`](https://github.com/jeff1evesque/machine-learning/blob/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/test/lint/eslint.json), unless there is already an issue open for that.  But, I think it may be good to roll that fix in this issue too.

**Comment by Vitao18** [comment]
> The travis ci is breaking during its linting process of eslint. I think you should take this opportunity to update eslint.json, unless there is an issue open for that. But, it may be better to roll that fix in this issue.

Sure!
I saw the rules and some of then will take a while to fix...
Is the linting rules in Travis a barrier an impeditive to merging the code?

**Comment by jeff1evesque** [comment]
3196666: what is this commit?

**Comment by jeff1evesque** [comment]
I undid your last commit, since that change did not make sense in this PR.

**Comment by Vitao18** [comment]
> 3196666: what is this commit?

Was trying to update the linting rules for the Travis-CI.
What do I have to do in this PR?

**Comment by jeff1evesque** [comment]
The travis ci [linter](https://github.com/jeff1evesque/machine-learning/blob/27eab3dee2ed13d68a4bf98d0ccc0ef30c872277/.travis.yml#L62), is predicated on default rules, along with custom overrides define from [`eslint.json`](https://github.com/jeff1evesque/machine-learning/blob/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/test/lint/eslint.json). I imagine based on the errors from the ci [build](https://travis-ci.org/jeff1evesque/machine-learning/builds/288511109), you'll need to tweak the [`eslint.json`](https://github.com/jeff1evesque/machine-learning/blob/582a03da2ccc1dcde2850be3574bbc25ec75e5a6/test/lint/eslint.json), to allow the build to pull request build to succeed.

**Comment by jeff1evesque** [comment]
To adopt the my changes, I think you'll need to `git pull origin feature-3047`, and `git pull upstream feature-3047`, before making any successive commits.

**Comment by jeff1evesque** [comment]
I will be doing a `vagrant up` build of your branch to test your changes right now.

**Comment by jeff1evesque** [comment]
Also, it seems you weren't successful in pulling my changes earlier, since you've repushed your old commits, on top of my adjustment. So, I'll reapply everything needed after you're finally done with the `eslint.json`.

**Comment by Vitao18** [comment]
> The travis ci linter, is predicated on default rules, along with custom overrides defined from eslint.json. I imagine from the ci build errors, you'll need to tweak the eslint.json, to have a successful travis build.

Sure!
So I need to configure the eslint.json to be equals the new linting rules we will be using?
Some of the errors won't go away, anyway. Is that fine?

**Comment by jeff1evesque** [comment]
Well, what you have configured is for a text editor. So, I think you added more than just eslint. The travis ci is only configured for the eslint, with respect to javascript, and reactjs. So, for it to pass the travis ci, I think if you tweak the eslint rules, by defining necessary overrides, it will clear up the travis ci errors.

**Comment by jeff1evesque** [comment]
For example, the `eslint.json` that travis uses:

```json
/**
 * eslint.json: this file provides a configuration of rules that eslint will
 *              implement, to validate 'jsx' files, when imported via the
 *              '-c [path/to/eslint.json]' flag.
 *
 * Note: eslint rules, and options are available:
 *
 *       https://github.com/yannickcr/eslint-plugin-react#configuration
 *       http://eslint.org/docs/rules/
 *
 * @max-len, corresponds to the following rules:
 *
 *     http://eslint.org/docs/user-guide/configuring#configuring-rules
 *     http://eslint.org/docs/rules/max-len#options
 *
 */
{
    "plugins": [
        "react"
    ],
    "parser": "babel-eslint",
    "rules": {
        "max-len": [2, {"code": 100, "tabWidth": 4, "ignoreUrls": true}],
        "react/display-name": 1,
        "react/forbid-prop-types": 1,
        "react/jsx-boolean-value": 1,
        "react/jsx-closing-bracket-location": 1,
        "react/jsx-curly-spacing": 1,
        "react/jsx-handler-names": 1,
        "react/jsx-indent-props": 1,
        "react/jsx-key": 1,
        "react/jsx-max-props-per-line": 1,
        "react/jsx-no-bind": 1,
        "react/jsx-no-duplicate-props": 1,
        "react/jsx-no-literals": 1,
        "react/jsx-no-undef": 1,
        "react/jsx-pascal-case": 1,
        "react/jsx-quotes": 1,
        "react/sort-prop-types": 1,
        "react/jsx-sort-props": 1,
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "react/no-danger": 1,
        "react/no-did-mount-set-state": 1,
        "react/no-did-update-set-state": 1,
        "react/no-direct-mutation-state": 1,
        "react/no-multi-comp": 1,
        "react/no-set-state": 1,
        "react/no-unknown-property": 1,
        "react/prefer-es6-class": 1,
        "react/prop-types": 1,
        "react/react-in-jsx-scope": 1,
        "react/require-extension": 1,
        "react/self-closing-comp": 1,
        "react/sort-comp": 1,
        "react/wrap-multilines": 1
    }
}
```

That probably is not the same rules as airbnb (I prefer 4 spaces vs 2, but that's not a big deal).

**Comment by jeff1evesque** [comment]
What if we replace the contents of [`.eslintrc.json`](https://github.com/Vitao18/machine-learning/blob/319666677c59ac2fbcfb4b5d50e113325cb5d0d6/src/.eslintrc.json), and embed:

```json
/**
 * eslint.json: this file provides a configuration of rules that eslint will
 *              implement, to validate 'jsx' files, when imported via the
 *              '-c [path/to/eslint.json]' flag.
 *
 * Note: eslint rules, and options are available:
 *
 *       https://github.com/yannickcr/eslint-plugin-react#configuration
 *       http://eslint.org/docs/rules/
 *
 * @max-len, corresponds to the following rules:
 *
 *     http://eslint.org/docs/user-guide/configuring#configuring-rules
 *     http://eslint.org/docs/rules/max-len#options
 *
 */
{
    "plugins": [
        "react"
    ],
    "parser": "babel-eslint",
    "rules": {
        "max-len": [2, {"code": 100, "tabWidth": 4, "ignoreUrls": true}],
        "react/display-name": 1,
        "react/forbid-prop-types": 1,
        "react/jsx-boolean-value": 1,
        "react/jsx-closing-bracket-location": 1,
        "react/jsx-curly-spacing": 1,
        "react/jsx-handler-names": 1,
        "react/jsx-indent-props": 1,
        "react/jsx-key": 1,
        "react/jsx-max-props-per-line": 1,
        "react/jsx-no-bind": 1,
        "react/jsx-no-duplicate-props": 1,
        "react/jsx-no-literals": 1,
        "react/jsx-no-undef": 1,
        "react/jsx-pascal-case": 1,
        "react/jsx-quotes": 1,
        "react/sort-prop-types": 1,
        "react/jsx-sort-props": 1,
        "react/jsx-uses-react": 1,
        "react/jsx-uses-vars": 1,
        "react/no-danger": 1,
        "react/no-did-mount-set-state": 1,
        "react/no-did-update-set-state": 1,
        "react/no-direct-mutation-state": 1,
        "react/no-multi-comp": 1,
        "react/no-set-state": 1,
        "react/no-unknown-property": 1,
        "react/prefer-es6-class": 1,
        "react/prop-types": 1,
        "react/react-in-jsx-scope": 1,
        "react/require-extension": 1,
        "react/self-closing-comp": 1,
        "react/sort-comp": 1,
        "react/wrap-multilines": 1
    }
}
```

**Comment by Vitao18** [comment]
I think it would solve the problem. I will try it local

**Comment by jeff1evesque** [comment]
I'm going to close this PR for now, and switch to another branch, so I can work on another issue.  Let me know when you're ready again, and need me to `vagrant up` your build, to test your changes.

**Comment by Vitao18** [comment]
@jeff1evesque copied the eslint.json file. think it'll fix the issue with the travis linter

**Comment by jeff1evesque** [comment]
Any updates on the `eslint.json`? When I resolve the following issues, I think I will close [milestone](https://github.com/jeff1evesque/machine-learning/milestone/6), and push the remaining issues to [milestone 0.7](https://github.com/jeff1evesque/machine-learning/milestone/7):

- https://github.com/jeff1evesque/machine-learning/issues/2869
- https://github.com/jeff1evesque/machine-learning/issues/1755

**Comment by Vitao18** [comment]
I would prefer creating a new branch and doing the PR withou messing with
the eslint.json(just changing reactCreateClass to ES6 classes)

2017-10-19 10:32 GMT-02:00 Jeff Levesque <notifications@github.com>:

**Comment by jeff1evesque** [comment]
Do you need help creating a new issue, in order to have a clean branch? If you prefer, you can close the existing issue, and simply reopen another.

**Comment by Vitao18** [comment]
I prefer to close the existing one and reopen another one.

**Comment by Vitao18** [comment]
I have created the new Issue:
https://github.com/jeff1evesque/machine-learning/issues/3079

**Pull request closed without merging**
