### PR TITLE
Roughed out example of how user_login should/could work.

### PR DESCRIPTION
**Pull request by doobeh**
This is just a rough-out example— I've not run it at all, so expect errors.  Your code is very verbose, and I'm not quite sure about some of your database choices, but hopefully my assumptions aren't too far off the mark. https://github.com/jeff1evesque/machine-learning/issues/2813

### CODE REVIEW

**Comment by jeff1evesque** [comment]
It still has the same earlier errors:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ mysql -u root -p db_machine_learning
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 77
Server version: 5.5.52-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db_machine_learning]> describe tbl_user ;
+-----------------+---------------+------+-----+---------+----------------+
| Field           | Type          | Null | Key | Default | Extra          |
+-----------------+---------------+------+-----+---------+----------------+
| id_user         | int(11)       | NO   | PRI | NULL    | auto_increment |
| username        | varchar(50)   | NO   | MUL | NULL    |                |
| email           | varchar(255)  | NO   |     | NULL    |                |
| password        | varchar(1069) | NO   |     | NULL    |                |
| datetime_joined | datetime      | NO   |     | NULL    |                |
+-----------------+---------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

MariaDB [db_machine_learning]> select * from tbl_user;
+---------+--------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| id_user | username     | email        | password                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | datetime_joined     |
+---------+--------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
|       1 | jeff1evesque | jeff1evesque | 0af1e16e19e432303c2dd501be814af2d335a06ba3f240d2f7fd678433d3024ad1b280b619aac213bc8d2c66b1a42da320bd6fa3f45de5aaf596033915e02319d767be408af32b164b58612eded105b3e79d4689e58a32d8ea8ce6595adde9867a50025f882bb616e27fa6affc8c3f98bff88ef26e9108eca862be9e6632f4b2c945a335f3abe4cddff2ceb77ec536090b2869d7e95136919c5d9c34bd665d5c9835e19b49e2d850bf9bc8c6b884aa9d548167cb609e445150fe20a6a68ff9d2bb259c682d2dbf9514508b8fba179a9d65295f84e2269fc208a5dcfe0fbcfa2fb62a0f9b7b257e7ca4d2aacfe9a2f57a745f3a20b97ff1ac30529576d5646a08611421ef25979296d265321a9038daa86e3e54dba50dcaebad85143161266d4e3d28a99b90c692bc447f24b9d031ca49ecf32bef93b91e5169e6284c7d751bdac13ac9bcbba6bce8d3bfa50f81c765c5e39ac7e4c1e9c73b20cdb9ee6f4ba87a6eac1c519baf96cdb635d36d5c945ad879ea05c6b0d4a5204f9fd88963e5219312b1f313d51a7c3d89cb13440f80475286860c85aab4c042c1722be9f78be2182eb078617c3b808b74167a5434ed54a2b54f36a1ec8295dd0766f55c8c3f7bc2ba97d536c3e7fac626817095cdd19a2766b3a7499f3cd459851a44fe7cc9dc2d7f75b3310af2d955570c1b3c1a10dbf68621340a7f40f6047e3b07a20fee4e56$a0HQm+9blEK6iULCXiTiW+4wDMEoazbpWXARqEhOMNk= | 2016-11-23 14:06:59 |
+---------+--------------+--------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
1 row in set (0.00 sec)

MariaDB [db_machine_learning]> exit
Bye
vagrant@vagrant-ubuntu-trusty-64:~$ (cd /vagrant && python app.py)
# login attempt (seems successful)
<flask_login.mixins.AnonymousUserMixin object at 0x7f0572ea5410>
<interface.model.User object at 0x7f0572ea53d0>
# going to browser and refreshing localhost:8080
<flask_login.mixins.AnonymousUserMixin object at 0x7f0572ea5210>
<flask_login.mixins.AnonymousUserMixin object at 0x7f05734fd750>
```

**Comment by doobeh** [comment]
Let me know the results of the print debugging-- that you're not getting any errors is almost magical :) but the SQL query must be failing in some way (not returning anything perhaps).

**Comment by jeff1evesque** [comment]
Your commits are not producing any output :(  So, I added uncommitted changes to `views.py`, containing additional `print` statements:


```python
@login_manager.user_loader
def load_user(uid):
    # local variables
    account = Retrieve_Account()
    user = account.get_user(uid)
    print 'user_loader- ', username, uid, email
...
@blueprint.route('/login', methods=['POST'])
def login():
    if request.method == 'POST':
        # local variables
        account = Retrieve_Account()
        username = request.form['user[login]']
        password = request.form['user[password]']
        uid = account.get_uid(username)['result']
        email = account.get_email(username)['result']
        print 'login- ', username, uid, email
...
```

The following is the corresponding output:

```bash
vagrant@vagrant-ubuntu-trusty-64:~$ (cd /vagrant && python app.py)
# login seems successful
login-  jeff1evesque 1 jeff1evesque
<flask_login.mixins.AnonymousUserMixin object at 0x7fe7ded10e10>
<interface.model.User object at 0x7fe7ded10dd0>
# refresh on localhost:8080
<flask_login.mixins.AnonymousUserMixin object at 0x7fe7ded10cd0>
```

I think the problem may be nestled into some combination of the constructs of `blueprint`, the app factory, and flask's `sessions` (or `flask-login`) not playing well with it.

**Note:** I did pull your code, and cleared the browser cache, prior to the above:

```bash
$ git remote -v
origin  https://jeff1evesque@github.com/jeff1evesque/machine-learning.git (fetch)
origin  https://jeff1evesque@github.com/jeff1evesque/machine-learning.git (push)
upstream        https://github.com/doobeh/machine-learning.git (fetch)
upstream        https://github.com/doobeh/machine-learning.git (push)

$ git pull upstream feature-2813
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/doobeh/machine-learning
 * branch            feature-2813 -> FETCH_HEAD
   361429d..3394879  feature-2813 -> upstream/feature-2813
Updating 361429d..3394879
Fast-forward
 brain/database/retrieve_account.py | 8 ++++++++
 1 file changed, 8 insertions(+)
```

**Comment by doobeh** [comment]
Okay, so digging in further— it looks like you haven't configured your LoginManager against your app ( https://flask-login.readthedocs.io/en/latest/#configuring-your-application )

You *do* create a registered login_manager in your `factory.py` but you never use it.  Instead you create a new one in `login.py` which you *don't* register against your app-- then you use that one as the basis of your login code, which is why the linkages aren't working.  You need to register the one you're using against your app, e.g.  `login_manager.init_app(current_app)`

**Comment by jeff1evesque** [comment]
I was trying to the [`login_manager`](https://github.com/jeff1evesque/machine-learning/blob/e5b91b5a5bbee7ec4c37292558f89719289440bd/factory.py#L21), and use the same instance from `factory.py`.  But, I'm still not sure if that's the correct implementation.

**Comment by jeff1evesque** [comment]
Yea, it seems that [`factory.py`](https://github.com/jeff1evesque/machine-learning/blob/e5b91b5a5bbee7ec4c37292558f89719289440bd/factory.py#L21), and [`views.py`](https://github.com/jeff1evesque/machine-learning/blob/a80329adb121372bfb01156b366cd2ce917f4c34/interface/views.py#L21), each `import` their own `login_manager`, which doesn't seem correct:

```python
from interface.login import login_manager
```

**Comment by jeff1evesque** [comment]
@doobeh, seems more likely that it's my constructs between the app factory, `blueprint`.  I've tried another [approach](https://github.com/jeff1evesque/machine-learning/issues/2819#issuecomment-262586247), with just the flask `session` implementation, which has similar results.

**Comment by jeff1evesque** [comment]
I think the following were some problems in my method in debugging:

- the `/index` route by default handles `GET` request
- setting a `session` via chrome browser, and in a separate terminal, trying to request that `session`
- the logout session implements `POST` request
  - but, I was attempting to implement logout via the browser `localhost:8080/logout` (i.e. `GET`)

Ultimately, since I'm implementing a single page application, the flask tendency to use templates is less of a practice for me.  Therefore, I tend to `return` json strings, and as reactjs parses it, it conditionally renders javascript components.  Currently, it's generally [recommended](http://stackoverflow.com/questions/3521290/logout-get-or-post) to use `POST` (instead of `GET`) requests.

Also, now that I'm looking at it, all I need is to store some unique identifier of the current user.  Flasks inherent `session` handles it.  So, I think not using `flask-login`, decreases the number of general, and build dependencies.  Since `flask-login` doesn't really [impose](https://flask-login.readthedocs.io/en/latest/) database logic:

>Impose a particular database or other storage method on you. You are entirely in charge of how the user is loaded.

I think I can just settle with a simpler `session` for now, and build additional database features, later in time.  Time will tell via #2818.  But, the `requests.Session()` [user testing](https://github.com/jeff1evesque/machine-learning/pull/2822#issuecomment-262789716), seem promising.

**Pull request closed without merging**
